// AUTO-GENERATED from docs/seo/legacy-url-migration-manifest.json by scripts/seo/build-manifest.mjs.
// Edge-safe redirect map (no fs/node). Used by middleware.
export interface EdgeRedirect { status: 301 | 410; target: string | null; }
export const REDIRECT_MAP: Record<string, EdgeRedirect> = {
  "/blog/free-moon-sign-calculator-discover-your-emotional-core-1": { status: 301, target: "https://cosmicspiritguide.com/blog/free-moon-sign-calculator-discover-your-emotional-core" },
  "/blog/free-moon-sign-calculator-discover-your-emotional-core-2": { status: 301, target: "https://cosmicspiritguide.com/blog/free-moon-sign-calculator-discover-your-emotional-core" },
  "/blog/free-zodiac-compatibility-calculator-find-your-cosmic-match-1": { status: 301, target: "https://cosmicspiritguide.com/blog/free-zodiac-compatibility-calculator-find-your-cosmic-match" },
  "/blog/free-zodiac-compatibility-calculator-find-your-cosmic-match-11": { status: 301, target: "https://cosmicspiritguide.com/blog/free-zodiac-compatibility-calculator-find-your-cosmic-match" },
  "/blog/how-to-read-your-birth-chart-a-beginner-s-visual-guide-1": { status: 301, target: "https://cosmicspiritguide.com/blog/how-to-read-your-birth-chart-a-beginner-s-visual-guide" },
  "/blog/how-to-read-your-birth-chart-a-beginner-s-visual-guide-2": { status: 301, target: "https://cosmicspiritguide.com/blog/how-to-read-your-birth-chart-a-beginner-s-visual-guide" },
  "/blog/love-compatibility-by-birth-date-the-complete-guide-1": { status: 301, target: "https://cosmicspiritguide.com/blog/love-compatibility-by-birth-date-the-complete-guide" },
  "/blog/love-compatibility-by-birth-date-the-complete-guide-5": { status: 301, target: "https://cosmicspiritguide.com/blog/love-compatibility-by-birth-date-the-complete-guide" },
  "/blog/mercury-retrograde-meaning-complete-survival-guide-1": { status: 301, target: "https://cosmicspiritguide.com/blog/mercury-retrograde-meaning-complete-survival-guide" },
  "/blog/mercury-retrograde-meaning-complete-survival-guide-2": { status: 301, target: "https://cosmicspiritguide.com/blog/mercury-retrograde-meaning-complete-survival-guide" },
  "/blog/numerology-compatibility-calculator-life-path-numbers-1": { status: 301, target: "https://cosmicspiritguide.com/blog/numerology-compatibility-calculator-life-path-numbers" },
  "/blog/numerology-compatibility-calculator-life-path-numbers-2": { status: 301, target: "https://cosmicspiritguide.com/blog/numerology-compatibility-calculator-life-path-numbers" },
  "/blog/rising-sign-calculator-find-your-ascendant-sign-free-2": { status: 410, target: null },
  "/blog/twin-flame-compatibility-test-are-they-your-other-half-1": { status: 301, target: "https://cosmicspiritguide.com/blog/twin-flame-compatibility-test-are-they-your-other-half" },
  "/blog/twin-flame-compatibility-test-are-they-your-other-half-2": { status: 301, target: "https://cosmicspiritguide.com/blog/twin-flame-compatibility-test-are-they-your-other-half" },
  "/coach": { status: 410, target: null },
  "/credits": { status: 410, target: null },
  "/dashboard": { status: 301, target: "https://cosmicspiritguide.com/login" },
  "/energy": { status: 410, target: null },
  "/forecasts": { status: 410, target: null },
  "/journal": { status: 410, target: null },
  "/moon-phase": { status: 301, target: "https://cosmicspiritguide.com/transits" },
  "/moon-reading": { status: 301, target: "https://cosmicspiritguide.com/tarot" },
  "/newsletter": { status: 410, target: null },
  "/subscription": { status: 410, target: null },
};
