import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildPaidNatalPdf, resolveFactAnchors, type PaidNatalPdfInput } from '@/lib/paidNatalPdf';

const signs = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const signFor = (longitude: number) => signs[Math.floor(longitude / 30) % 12];
const positions = ['sun', 'moon', 'mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto', 'chiron', 'juno', 'northnode', 'southnode', 'ascendant', 'descendant', 'midheaven', 'icumcoeli'];
const positionFacts = Object.fromEntries(positions.map((key, i) => { const longitude = ({ ascendant: 74, descendant: 254, midheaven: 344, icumcoeli: 164 } as Record<string, number>)[key] ?? (i * 19.5) % 360; const house = ({ ascendant: 1, descendant: 7, midheaven: 10, icumcoeli: 4 } as Record<string, number>)[key] ?? (Math.floor((((longitude - 74) + 360) % 360) / 30) + 1); return [`natal.${key}.position`, { id: `natal.${key}.position`, kind: 'position', display: `${key} placement`, value: { key, label: key, longitude, sign: signFor(longitude).toLowerCase(), signLabel: signFor(longitude), degreeInSign: longitude % 30, house } }]; }));
const houseFacts = Object.fromEntries(Array.from({ length: 12 }, (_, i) => [`common.cusp.${i + 1}`, { id: `common.cusp.${i + 1}`, kind: 'point', display: `House ${i + 1} cusp`, value: { num: i + 1, cuspLongitude: (74 + i * 30) % 360, sign: signFor((74 + i * 30) % 360).toLowerCase(), signLabel: signFor((74 + i * 30) % 360) } }]));
const input: PaidNatalPdfInput = { title: 'Natal Birth Chart Report', name: 'Ethan', birth: { date: '1980-03-09', time: '10:30', location: 'Santa Cruz, CA' }, facts: { ...positionFacts, ...houseFacts, 'natal.sun.position': { id: 'natal.sun.position', display: 'Sun in Pisces 18deg42', value: { key: 'sun', longitude: 348.7, signLabel: 'Pisces', degreeInSign: 18.7 } }, 'natal.moon.position': { id: 'natal.moon.position', display: 'Moon in Cancer 2deg10', value: { key: 'moon', longitude: 92.16, signLabel: 'Cancer', degreeInSign: 2.16 } } }, ledger: { positions: Object.values(positionFacts) as any, houses: Object.values(houseFacts).map((f: any) => f.value), aspects: [], elements: { Fire: 3, Earth: 4, Air: 1, Water: 2 } }, sections: [{ heading: 'Core Identity', body: 'Your signature is [[natal.sun.position]].' }, { heading: 'Emotional Landscape', body: 'Your inner tide is [[natal.moon.position]].' }] };
describe('paid natal PDF vertical slice', () => {
  it('resolves every fact anchor using the authoritative display value', () => { const result = resolveFactAnchors(input.sections, input.facts); expect(result.sections[0].body).toContain('Sun in Pisces'); expect(result.unresolved).toEqual([]); });
  it('fails closed when any anchor is missing', () => { expect(() => resolveFactAnchors([{ heading: 'Bad', body: '[[missing.fact]]' }], input.facts)).toThrow(/unresolved fact anchors/); });
  it('rejects partial placement input instead of drawing a misleading wheel', () => { const partial = { ...input, ledger: { ...input.ledger!, positions: input.ledger!.positions.slice(0, 3) } }; expect(() => buildPaidNatalPdf(partial)).toThrow(/complete natal placement ledger/); });
  it('rejects unresolved chart data instead of falling back to scaffold geometry', () => { const unresolved = { ...input, ledger: { ...input.ledger!, houses: input.ledger!.houses.slice(0, 11) } }; expect(() => buildPaidNatalPdf(unresolved)).toThrow(/12 houses/); });
  it('generates a controlled PDF with a full wheel, ledger data, and blueprint hierarchy', () => { const pdf = buildPaidNatalPdf(input); writeFileSync(join(process.cwd(), 'tests/reports/fixtures/generated-paid-natal.pdf'), pdf); const text = new TextDecoder().decode(pdf); expect(text.startsWith('%PDF-1.4')).toBe(true); expect(text).toContain('COSMIC BLUEPRINT'); expect(text).toContain('12 HOUSES'); expect(text).toContain('House 12'); expect(text).toContain('southnode  Sagittarius'); expect(text).toContain('ELEMENT BALANCE'); expect(text).toContain('ASPECT MODEL: major aspects, 10deg orb'); expect(text).toContain('NO VERIFIED ASPECTS'); expect(text).not.toContain('[[natal.'); expect(text).not.toContain('about:blank'); });
});
